from pathlib import Path
import sys

# Add project root so "src" is importable
_root = Path(__file__).resolve().parent.parent
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

from src.baseline.rule_based import RuleBasedExplainer
from src.models.inference import CompilerErrorExplainer
from src.utils.config import Config
from src.utils.logger import setup_logger

logger = setup_logger()

class HybridExplainer:
    def __init__(self, model_path: Path = None):
        self.rule_based = RuleBasedExplainer()
        self.nlp_based = CompilerErrorExplainer(model_path=model_path)
    
    def explain(self, error_message: str) -> str:
        # 1. Try rule-based first
        rule_explanation = self.rule_based.explain(error_message)
        
        # If rule-based matched something specific (not Unknown Error)
        if "Category: Unknown Error" not in rule_explanation:
            return f"{rule_explanation}\n(Explanation generated by Rule-Based System)"
        
        # 2. Fallback to NLP-based if rule-based failed
        logger.info("Rule-based system failed to categorize. Falling back to NLP-based system.")
        
        # Use the simple prompt format the model was trained on
        nlp_explanation = self.nlp_based.explain(error_message)
        
        return f"The compiler reports: {error_message}\n\n{nlp_explanation}\n(Explanation generated by NLP System)"

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Hybrid Compiler Error Explainer")
    parser.add_argument('--error', type=str, required=True, help="Compiler error message")
    parser.add_argument('--model-path', type=str, default=None, help="Path to trained T5 model")
    
    args = parser.parse_args()
    
    model_path = Path(args.model_path) if args.model_path else None
    explainer = HybridExplainer(model_path=model_path)
    print(explainer.explain(args.error))
